### ISSUE TITLE
untyped js being closured causing issue

### ISSUE THREAD

**Issue by hoseyjoe** [back2dos/closure#10]
I am trying to use advanced optimization and using this jquery call in haxe
`untyped __js__("$.stuff.Dialog.validateInput()");`
It is throwing
`Cannot read property 'ca' of undefined `
because it is being closured to
`$.da.ca.ia()`

Any thoughts on how to avoid that? Removing advanced allows it to work

**Comment by hoseyjoe** [comment]
Changing it to 
`untyped __js__("eval('$.stuff.Dialog.validateInput()')")`
fixed my issue. Wondering if there may be a more haxian way of doing it?

**Comment by back2dos** [comment]
Well, you have two options:

1. Don't use advanced mode
2. Use [closure externs](https://developers.google.com/closure/compiler/docs/api-tutorial3) to avoid certain fields things from being renamed.
