### ISSUE TITLE
-D closure_off

### ISSUE THREAD

**Issue by tong** [back2dos/closure#4]
How about adding such flag to turn off closure compilation?
Haxe defines more likely get generated by a build process than the -lib parameter.
Well, it would be a welcome feature for my build process :smile:

**Comment by back2dos** [comment]
Is this really a thing? Adding it will hardly be a problem, but instinctively it seems a bit awkward.

**Comment by back2dos** [comment]
Well, believe it or not, I've run into a similar situation just now. Will add this over the weekend ;)

**Comment by tong** [comment]
I told you so :)
