### ISSUE TITLE
 how to keep an @:Expose

### ISSUE THREAD

**Issue by hoseyjoe** [back2dos/closure#5]
It looks like you have to make an extern.js and then call it from the command line

extern.js which contains textDiv will keep it from being renamed
function textDiv(text){};

compile with
`Sys.command('java', ['-jar', jar, 
      #if closure_prettyprint '--formatting=pretty_print', #end
      '--compilation_level', #if closure_advanced 'ADVANCED' #else 'SIMPLE' #end,
      '--js', out,
      '--js_output_file', min,
      '--externs','extern.js',`

Ill try to make a pull request

**Comment by hoseyjoe** [comment]
`Sys.command('java', ['-jar', jar, 
      #if closure_prettyprint '--formatting=pretty_print', #end
      '--compilation_level', #if closure_advanced 'ADVANCED' #else 'SIMPLE' #end,
      '--js', out,
      '--js_output_file', min,
      #if closure_externs
      '--externs','extern.js',
      #end
    ]);`

This is what I did and then used compiler switch "-D closure_externs".  This requires a extern.js in the root folder.  Not sure how to make it so you can pass in a path through the compiler switch.

extern.js contains list of extern functions like function textDiv(text){}; function textDiv2(text){}; separated by line breaks.

Random note.  I removed the !out.endsWith('.js') section since I am compiling to aspx page where translations happen. It would be nice to make that optional

**Comment by hoseyjoe** [comment]
added pull request "added externs and removed requirement for .js file"

**Comment by back2dos** [comment]
I assume this can be closed then?

**Comment by hoseyjoe** [comment]
yes, thank you
